### ISSUE TITLE
"Copy retrospective link" does not escape spaces 

### ISSUE THREAD

**Issue by Adam-Brinded** [microsoft/vsts-extension-retrospectives#122]
An Azure DevOps project i use has a space in the project name. 
When copying the link to a restrospective the output does not escape the space, resulting in a broken link.

Example:
Project name: Test Project
output from "Copy retrospective link": https://dev.azure.com/<organization>/Test Project/_apps/hub/ms-devlabs.team-retrospectives.home?teamId=<team-id>boardId=<boardId>
Desired output: https://dev.azure.com/<organization>/Test%20Project/_apps/hub/ms-devlabs.team-retrospectives.home?teamId=<team-id>boardId=<boardId>

**Comment by ErikHansen1** [comment]
I'd like to reiterate that when you choose "Copy Retrospective" option on the A.D.O. Retrospective board it yields a link that is broken due to a space that's coded in there.
![Copy retro link button](https://user-images.githubusercontent.com/76187806/105402169-f61d1a80-5bdb-11eb-90bd-9df30345aa20.png)
![Broken retro link](https://user-images.githubusercontent.com/76187806/105402215-0208dc80-5bdc-11eb-982a-6d0e92f4965f.png)

**Comment by robagale** [comment]
Also want to highlight this. I need to use the link to paste into my team chat to get everyone into the Retrospective in a timely manner.

**Comment by Adam-Brinded** [comment]
This appears to be resolved by PR #271  (https://github.com/microsoft/vsts-extension-retrospectives/pull/271)

**Comment by ErikHansen1** [comment]
Thank you for getting this PR in. I just tested is out, @Adam-Brinded , and the fix works like a charm.

**Comment by robagale** [comment]
Noticed the fix the other day. Much appreciated.
