### ISSUE TITLE
Is there a way to restrict access to retrospectives to only certain members?

### ISSUE THREAD

**Issue by drbblbibble** [microsoft/vsts-extension-retrospectives#299]
I have a project with many people on it, stakeholders, devs, etc. I love the retro feature, but want to limit it to only the devs. How can I approach this?

**Comment by nisancigokmen** [comment]
I will be glad if you can contact me. I would like to consider your opinion. :))

**Comment by cookyrag** [comment]
This would be a fantastic feature , we use a centralised DevOps board and have external client access so would like to restrict access to the Retro boards as well

**Comment by SilkeBU** [comment]
Same for us -  we are also interested in this. Would be a good feature to restrict access to Retro board.

**Comment by maxschaefer28** [comment]
I tried to restrict the access by setting up an own Team "ProjectXYZ-Retros" and only added the dev team however still all people can see it under "All Teams", select it and see all the retro items. Do you think there could be a way with an own team or is there some kind of new feature? I think its essential because the retro should be a safe place for the dev team.

**Comment by DasSmad** [comment]
Same here.
pls consider a permissionsystem to limit access

**Comment by dstoddar** [comment]
Thank you for the feedback. We are currently building a new backend to the retrospective. Once complete, we are evaluating and prioritizing the full list of requests. Limiting access to retrospectives to only team members as an option at retrospective set-up is fairly high on our priority list upon release of the new backend which is planned in the coming weeks.
