### ISSUE TITLE
Links generated via "copy retrospective link" does not take you to the retrospective board

### ISSUE THREAD

**Issue by Dan-Albrecht** [microsoft/vsts-extension-retrospectives#50]
On a board I want to share with my team, I click on the "Copy retrospective link" command. A link in following form is generated:

`https://dev.azure.com/?teamId={{some guid}}&boardId={{another guid}}`

Navigating to that link dumps me on the organization page for whatever I was looking at last, not the retrospective board. E.g.:

`https://dev.azure.com/{{the organization}}/`

**Comment by thomasvdb** [comment]
I can't reproduce this issue.
Are you pasting the URL in another browser of just another tab?

**Comment by Dan-Albrecht** [comment]
Another tab.

**Comment by pedropaulovc** [comment]
I can reproduce the issue as well. @thomasvdb are you a Microsoft engineer? I can ping you an URL of my team's retrospective board for you to check what's going on.

**Comment by thomasvdb** [comment]
@pedropaulovc No, I'm not a Microsoft engineer. Just following this in my spare time :) 
Can you reproduce it consistently or in specific cases?

**Comment by pedropaulovc** [comment]
I can reproduce it consistently. It seems that the problem is in https://github.com/microsoft/vsts-extension-retrospectives/blob/b3f5c635370efa79ff06c51de7609cbf7b8cfcd6/RetrospectiveExtension.Frontend/utilities/boardUrlHelper.tsx#L7

in our environment, `document.referrer` is just `"https://dev.azure.com/"` which seems to not capture all information necessary for the URL to work properly.

**Comment by thomasvdb** [comment]
Can you share the URL (or format of the URL if you want to hide some information) of your retrospective page?
Not the link that is copied but the URL when you navigate to your retrospective board.

**Comment by pedropaulovc** [comment]
Sure, this is my personal sandbox environment: https://dev.azure.com/pevezzac/CloudAdoptionPlanV0/_apps/hub/ms-devlabs.team-retrospectives.home

**Comment by cachapman** [comment]
Same boat - I notice a 302 when navigating to the copied board link.

**Comment by vinaysandela** [comment]
"Copy retrospectives Link" routing to Collection Page. Cleared Cache and tried on multiple browsers and users. Got Org Admin access. Can you please help. Thanks

**Comment by courtyjones** [comment]
I'm experiencing this same issue as well

**Comment by TheDarlek** [comment]
We are seeing the same problem but it does seem to be Chromium browsers, Chrome/Edge, which are showing the problem - Firefox is fine

**Comment by mbryantII** [comment]
The problem is worse on Chrome based browsers, however the GUIDs that are associated with the link dont seem to make any difference into where you are navigated too.  You are always directed to the last board that you were looking at, which i dont believe to be the intended behavior.

for example:
`https://dev.azure.com/<org>/<team>/_apps/hub/ms-devlabs.team-retrospectives.home?teamId=20cb57ca-8f3c-4136-b02d-1cce999e5da7&boardId=179a600a-b271-4ca1-9e80-3a0d94be19f0`

and

`https://dev.azure.com/<org>/<team>/_apps/hub/ms-devlabs.team-retrospectives.home?teamId=4767f119-9ef7-4fb5-bbe3-e06e593debb4&boardId=e596ca0c-6edf-4a88-a1f9-446f883e66cd`

will nvigate to the same board.

**Comment by mdg357** [comment]
I was able to reproduce the issue on both Google Chrome (80.0.3987.122) and Firefox (81.0.1).

The link generated is of the form `https://dev.azure.com/?teamId=<guid>&boardId=<guid>`.

If pasted into the address bar, I'm redirected to the home page for the organization (e.g. `https://dev.azure.com/<organization_name>/`).

It may be worth noting that the project this is under has been renamed at some point in the last few months. I'm unsure if that has anything to do with it, but that is the only major change I can think of.

**Comment by ericstj** [comment]
My team is facing the same problem.  Curious if anyone has this working: what's the expected way to pass query parameters to this app?  Trying to understand if the problem is with the URL formatting or the routing on the app side.

**Comment by mgagan99** [comment]
Works fine in Firefox but not in Edge. The link itself is different. E.g.

**Firefox:**
https://dev.azure.com/gaganmaheshwari/CNC%20Toolpathing/_apps/hub/ms-devlabs.team-retrospectives.home?teamId=e3f213bc-f1e9-450e-bae2-0bf8ee23c94d&boardId=883610a3-ff24-4500-985d-ab27b37a2957

**Edge:**
https://dev.azure.com/?teamId=e3f213bc-f1e9-450e-bae2-0bf8ee23c94d&boardId=883610a3-ff24-4500-985d-ab27b37a2957

**Comment by jamshedd** [comment]
Has anyone gotten this working with a handcrafted URL? I tried adding the teamId and boardId parameters to the URL but that still doesn't take me to the correct retrospective board if its the first time. It looks like parameters don't matter, I always end up on the board I last used.

**Comment by svanamali** [comment]
Is there an update on this issue? We have been noticing this at least a month now. This issue is consistent and reproducible all the time.

**Comment by MJZawacki** [comment]
I'm seeing the same issue with a few different teams

**Comment by srwoolc** [comment]
I've got the same issue.

**Comment by todubble1** [comment]
> Has anyone gotten this working with a handcrafted URL? I tried adding the teamId and boardId parameters to the URL but that still doesn't take me to the correct retrospective board if its the first time. It looks like parameters don't matter, I always end up on the board I last used.

I was able to munge an existing Retrospective home URI, and the explicit teamid to get a shareable link in Edge.  I followed the example in mgagan99's response above.

**Comment by cstrempfer** [comment]
Check the Q&A section in Visual Studio Marketplace. There are a lot of complaints about this, therefore it doesn't seem to be an edge case. https://marketplace.visualstudio.com/items?itemName=ms-devlabs.team-retrospectives&ssr=false#qna

Manually adjusting the URL doesn't help, because it's taking you to the last viewed retrospective as was noted above. This is the major issue, if we can fix the routing then adjusting the "copy link" button should be easy.
