### ISSUE TITLE
Use Retrospectives to request and record team happiness and team knowledge levels

### ISSUE THREAD

**Issue by GeertLommers** [microsoft/vsts-extension-retrospectives#51]
Part of productivity is related to individual and team happiness in combination with level of knowledge.

As a product owner I want to help the team to improve by asking them to fill in an individual happiness form related to the last print time. The average team figure indicates the team happiness. Same applies to the knowledge level, wich indicated the need for training.
I tried to accomodate this in the retrospective plugin, but it did not work out so far. 

This based on the book mentionned below.

(1)   Oswald A.J., Proto, E., Sgroi, D., “Happiness and Productivity”, University   of Warwick, UK, and IZA Bonn, Germany JOLE 3rd Version, 2014
--

**Comment by ArieHein** [comment]
We used to have that as a daily pool in our slack channel. We then added a small web site with a db to aggregate reports but it was extremely subjective as to that causes that led to the overall components of happiness.

Do you really want to have that as a one time thing? is retrospective the place for that ? What will you measure by having this at the end of this sprint ? if anything it would be an "average" (?) of the happiness over time. Some of which is not even relevant to the project content ("had a bad day, got a puncture in my wheel on way to work so couldn't spend enough time on this task which in itself is very complex to begin with.."). So my bad mark for happiness would be why ? cause the task is complex or because i had a bad real life event?

Productivity is measured in other ways already, 

At general, I would say none of these actually belongs in a retrospective. One is extremely subjective, I could have a great day overall but one task I kept banging my head upon. As always its very subjective and the later parts of the sprint might have different average results compared to the start of the sprint, especially if production bugs pop in the middle of the sprint or towards the end when stress comes into play more.

Productivity is not subjective, its a quantitative measure. We had X many user stories to complete, Y many Story Points, we estimated Z hours and we used <Z hours, our burndown graphs looks spot on, and more measure points like Code Coverage and failed builds / tests rates etc etc.  My 0.5 cent.

**Comment by Sannevdwal** [comment]
Hi ArieHein,

Thanks for your reply. 
There is defenitely a releation between happy employees/ teams and the success of organisations. More happy employees are more productive, motivated and also more healthy. To know what the state is of happiness you need te measure it. We decided to measure this by a questionairy. In a retrospective the output is the central document we will talk about openly. For negative scores we make actionpoints for the next sprint(s). 

Happiness is not only about a high productivity. Maybe the productivity is good but will be even much higher when employees are more happy or low happiness can cause problems in the long end and not just on that moment. By using a questionary specially for happiness you can act proactive and make together your team better.

It would be really nice to use Devops for this function. It is important for the overview to use one tool as many as possible instead of different tools for different measurements. Most important here is that there would be a way to show the happiness data in the Dashboard tool + the actions we discussed about dropped in the retrotool.

**Comment by polatengin** [comment]
since this issue has low interaction and doesn't seem to related to the "core" functionality of the retrospective tool, I'm closing it for now.

please feel free to add a comment and re-open it.
