### ISSUE TITLE
Focus Mode is not working after the last release update

### ISSUE THREAD

**Issue by EmanMos** [microsoft/vsts-extension-retrospectives#80]
After the new release update, the focus mode now is not working.
It displays a blank page, screen:

![image](https://user-images.githubusercontent.com/67954813/101165145-7391c900-3636-11eb-877b-6a61e74ee4fc.png)

**Comment by GunnyDev** [comment]
Have the same issue here, perfect timing for our Retro Meeting in an hour.

**Comment by EmanMos** [comment]
> Have the same issue here, perfect timing for our Retro Meeting in an hour.

It was a surprise for the team in the meeting, not a good situation. Even the new UI is meh :(

**Comment by polatengin** [comment]
hey @EmanMos , @GunnyDev , thanks for reporting this issue. sorry for inconvenience, I didn't notice the issue. currently working on it.

biggest update to the extension with this release is, underlying sdk bumped to the latest version, UI is now supporting themes.

I know I need to polish a lot of things in the UI, since this release is out, I'll focus polishing those areas.

as said, I'll fix Focus Mode UI, asap.

_PS : I shouldn't release on Friday 🤦‍♂️_

**Comment by EmanMos** [comment]
> hey @EmanMos , @GunnyDev , thanks for reporting this issue. sorry for inconvenience, I didn't notice the issue. currently working on it.
> 
> biggest update to the extension with this release is, underlying sdk bumped to the latest version, UI is now supporting themes.
> 
> I know I need to polish a lot of things in the UI, since this release is out, I'll focus polishing those areas.
> 
> as said, I'll fix Focus Mode UI, asap.
> 
> _PS : I shouldn't release on Friday 🤦‍♂️_

oh, thank you very much @polatengin for that very quick response, and your willing to fix those issues quickly.
Much appreciated!

**Comment by GunnyDev** [comment]
Thanks @polatengin , feel free to ping me to confirm its working our end.

**Comment by GunnyDev** [comment]
@polatengin I can confirm this is now resolved for us, many thanks.
