### ISSUE TITLE
The retrospective extension take too long time to load and view

### ISSUE THREAD

**Issue by sinnypan** [microsoft/vsts-extension-retrospectives#868]
**Describe the bug**
We found that the retrospective take longer time to load recently. Sometimes it took ~1 min to load completed. We are using Azure DevOps Service. And we're MS product team using the same org that every Azure org using.

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[x ] No

If Yes, what version of the extension?

**To Reproduce**

1. Click "Retrospective" on Azure DevOps project
2. The new window start loading, and it will take a lot of time, 1 min+

**Expected behavior**
Should be shown within second(s)

**Screenshots**
NA

**What screen type are you seeing this on ?**
[x ] Desktop
[ ] Mobile

**Additional context**

**Comment by glennmusa** [comment]
Perhaps instead of [fetching every team in a project](https://github.com/microsoft/vsts-extension-retrospectives/blob/07b0346c90313d00330e382d1e475781ce4a3402/src/frontend/dal/azureDevOpsCoreService.tsx#L52-L73), the [`$mine`](https://learn.microsoft.com/en-us/rest/api/azure/devops/core/teams/get-all-teams?view=azure-devops-rest-7.1&tabs=HTTP#uri-parameters) query option on the `/teams` API could be useful for fetching teams specific to a user.
