### ISSUE TITLE
[Feature request] Allow to save & reuse custom Board Templates

### ISSUE THREAD

**Issue by oliveratgithub** [microsoft/vsts-extension-retrospectives#88]
As follow-up to #35 : it would be nice to be able to save a custom column configuration (color, icon, column name, number of columns) into the "Board Templates" to re-apply from templates for a new Retrospective board.

**Comment by polatengin** [comment]
it's a very good suggestion.

do you have a "custom" board template for your retrospectives? I'm asking this to understand if I missed a common template? 😄 

or did you mean for ad-hoc retros?

**Comment by oliveratgithub** [comment]
> do you have a "custom" board template for your retrospectives? I'm asking this to understand if I missed a common template? 😄

I use with my scrum team an adaption of a common model as you provide in the templates:
KEEP / START / STOP

But the thing is also that we write it in German - so you could tackle „translations“ also by offering custom templates to be saved 😉

E.g.: from my retros with [color / icon]
* [green / smiley] `KEEP mir gefiel dass...`
* [blue / discuss] `START wir sollten...`
* [orange / exclamation] `STOP es hinderte mich...`

**Comment by polatengin** [comment]
I was going to add KEEP/START/STOP, then I noticed, there is already Start/Stop/Continue template. since they're super close, I'm skeptical to add a template very similar.

But I'll work on to support custom templates.

Do you think custom templates should be user specific or team specific or org specific?

**Comment by oliveratgithub** [comment]
> Do you think custom templates should be user specific or team specific or org specific?

Team-specific would be best IMHO.

**Comment by briannaritter** [comment]
If this feature has not rolled out yet, could I please request that a template be added with the below columns:
- What went well
- What didn't go well
- What can we improve?
- What we'll commit to

My organization uses those columns heavily, and since we can't add custom columns and have the column name save currently, this would be a huge help.

Thank you!
Brianna

**Comment by oliveratgithub** [comment]
> since we can't add custom columns and have the column name save currently, this would be a huge help.

@briannaritter just use the `Return`-key to save custom column names (basically like to confirm the input)

**Comment by boukepieter** [comment]
I would also like this feature. We are using: Grades | What went well | What didn't go well | Actions/Decisions

**Comment by DennisvdPluijm** [comment]
Similar request here: https://github.com/microsoft/vsts-extension-retrospectives/issues/130

**Comment by mindlessroman** [comment]
#300 is consolidating these. Will close here - Follow along there!

**Comment by ThatKasper** [comment]
How about simply letting us create a custom board & save it as a template?? having to type the same board over & over every 2 weeks is driving me mad. Multiple folks across our organization also wish for a way to create/edit templates or at least be able to cope the last one we created.
