### ISSUE TITLE
Copied retrospective link navigates to last visited board instead of the specific retrospective board

### ISSUE THREAD

**Issue by IMRens** [microsoft/vsts-extension-retrospectives#95]
When using the menu to 'Copy retrospective link' you get a link that looks like this: 

_https://dev.azure.com/{org}/{project}/_apps/hub/ms-devlabs.team-retrospectives.home?teamId={teamId}&boardId={boardId}_

If you copy the retrospective link (boardId=A) switch to another board for the same team and copy the retrospective link again you will now have two different links (boardId=A and boardId=B).

Lets say the users last visited board is A. If a user navigates to the link with boardId=B the user will end up on board A.

It seems like the boardId is completely ignored. Instead every link navigates to the last visited board.

**Comment by EmanMos** [comment]
I also have this issue.

**Comment by cstrempfer** [comment]
This behaviour was already mentioned in #50. I suggest to reopen that one, because it contains more details.

**Comment by IMRens** [comment]
> This behaviour was already mentioned in #50. I suggest to reopen that one, because it contains more details.

I will close this one if #50 can be reopened by some who can.

**Comment by jpbufe3** [comment]
@cstrempfer @IMRens - I believe #50 was actually referencing a different problem, which has already been fixed. The other issue was describing that the generated URL from the copy button was incorrect, whereas this issue is saying that even with the correct URL, it is not taking you to the correct board (the URL query parameters are not being respected). I think this is a separate issue that needs to be addressed still.

**Comment by cstrempfer** [comment]
@jpbufe3 I don't care much where it's tracked as long as it gets fixed somehow. Imho #50 is not specific to one of the two bugs, because it wasn't obvious that there is more than one.
